apiVersion: apps/v1
kind: Deployment
metadata:
  name: developers-api
spec:
  selector:
    matchLabels:
      app: developers-api
  template:
    metadata:
      labels:
        app: developers-api
    spec:
      containers:
      - name: developers-api
        env:
          - name: ConnectionString__outage-api
            value: "http://outagetracker-api-service"
        image: developers-api:v0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
